issue: dict = {
    "url": "https://api.github.com/repos/Findy-U/ProdOps/issues/70",
    "repository_url": "https://api.github.com/repos/Findy-U/ProdOps",
    "labels_url": "https://api.github.com/repos/Findy-U/ProdOps/issues/70/labels{/name}",
    "comments_url": "https://api.github.com/repos/Findy-U/ProdOps/issues/70/comments",
    "events_url": "https://api.github.com/repos/Findy-U/ProdOps/issues/70/events",
    "html_url": "https://github.com/Findy-U/ProdOps/issues/70",
    "id": 1793822382,
    "node_id": "I_kwDOJpY3V85q646u",
    "number": 70,
    "title": "Adição de testes para funções do webhook.",
    "user": {
        "login": "Demian143",
        "id": 81446007,
        "node_id": "MDQ6VXNlcjgxNDQ2MDA3",
        "avatar_url": "https://avatars.githubusercontent.com/u/81446007?v=4",
        "gravatar_id": "",
        "url": "https://api.github.com/users/Demian143",
        "html_url": "https://github.com/Demian143",
        "followers_url": "https://api.github.com/users/Demian143/followers",
        "following_url": "https://api.github.com/users/Demian143/following{/other_user}",
        "gists_url": "https://api.github.com/users/Demian143/gists{/gist_id}",
        "starred_url": "https://api.github.com/users/Demian143/starred{/owner}{/repo}",
        "subscriptions_url": "https://api.github.com/users/Demian143/subscriptions",
        "organizations_url": "https://api.github.com/users/Demian143/orgs",
        "repos_url": "https://api.github.com/users/Demian143/repos",
        "events_url": "https://api.github.com/users/Demian143/events{/privacy}",
        "received_events_url": "https://api.github.com/users/Demian143/received_events",
        "type": "User",
        "site_admin": False
    },
    "labels": [

    ],
    "state": "open",
    "locked": False,
    "assignee": {
        "login": "Demian143",
        "id": 81446007,
        "node_id": "MDQ6VXNlcjgxNDQ2MDA3",
        "avatar_url": "https://avatars.githubusercontent.com/u/81446007?v=4",
        "gravatar_id": "",
        "url": "https://api.github.com/users/Demian143",
        "html_url": "https://github.com/Demian143",
        "followers_url": "https://api.github.com/users/Demian143/followers",
        "following_url": "https://api.github.com/users/Demian143/following{/other_user}",
        "gists_url": "https://api.github.com/users/Demian143/gists{/gist_id}",
        "starred_url": "https://api.github.com/users/Demian143/starred{/owner}{/repo}",
        "subscriptions_url": "https://api.github.com/users/Demian143/subscriptions",
        "organizations_url": "https://api.github.com/users/Demian143/orgs",
        "repos_url": "https://api.github.com/users/Demian143/repos",
        "events_url": "https://api.github.com/users/Demian143/events{/privacy}",
        "received_events_url": "https://api.github.com/users/Demian143/received_events",
        "type": "User",
        "site_admin": False
    },
    "assignees": [

    ],
    "milestone": None,
    "comments": 0,
    "created_at": "2023-07-07T16:24:05Z",
    "updated_at": "2023-07-07T16:25:00Z",
    "closed_at": None,
    "author_association": "COLLABORATOR",
    "active_lock_reason": None,
    "body": "Primeiramente deve ser definida a biblioteca de testes a ser utilizada, a seguir a adição dos testes para as funções parse_hook e process_hook, verificando os tipos de entrada e saida.",
    "reactions": {
        "url": "https://api.github.com/repos/Findy-U/ProdOps/issues/70/reactions",
        "total_count": 0,
        "+1": 0,
        "-1": 0,
        "laugh": 0,
        "hooray": 0,
        "confused": 0,
        "heart": 0,
        "rocket": 0,
        "eyes": 0
    },
    "timeline_url": "https://api.github.com/repos/Findy-U/ProdOps/issues/70/timeline",
    "performed_via_github_app": None,
    "state_reason": None
}
